### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by crisgarner** [diglos/pi-gen#8]
Some information I would like to know is "How to update the software" Eg. Prysm. How can I edit or run the systemctl with flags for eg. --graffiti or --medalla

**Comment by RP4-8gb** [comment]
I would also greatly appreciate some advice on how to switch to the Medalla testnet. In a Reddit post (diglos76) it was mentioned that work is being done on a completely new pre-installed server image. Is there any eta for this?

I have ran the pre-installed server (Onyx) image and this was a very good experience. I also tried to build it myself for Medalla testnet but found that syncing the beacon chain took easily 6 times longer, among other issues caused by my lack of knowledge.

It seems that the latest pre-installed server script could be tweaked to work with the new prysm installation script. But perhaps that is complete nonsense. Is this something I can do myself @diglos?

**Comment by diglos** [comment]
We are in the process of releasing a gitbook style with more detailed documentation.
